### ISSUE TITLE
Mise en forme de la fiche d'inscription

### ISSUE THREAD

**Issue by davy39** [Lycee-Experimental/django-lxp#9]
Hello !
Une nouvelle issue pour discuter de la mise en forme de l'appli : les formulaires, l'affichage des fiches d'inscriptions et donc des PDFs, les tableaux pour visualiser les données. 

Pour connaitre le principe de la génération du PDf et de sa mise en forme, voir [cet article du wiki](https://github.com/Lycee-Experimental/django-lxp/wiki/5.-Mise-en-forme-de-la-fiche-d'inscription).

## TODO
- [ ] Faire le tri des champs à afficher sur la fiche d'inscription, et établir sur le papier la forme que l'on veut lui donner.
- [ ] Modifier la structure du [template de la fiche d'inscription](https://github.com/Lycee-Experimental/django-lxp/blob/main/templates/inscription/fiche_inscription.html) (html)
- [ ] Peaufiner l'allure de la fiche à partir du [css utilisé](https://github.com/Lycee-Experimental/django-lxp/blob/main/static/css/pdf.css) pour la génération du pdf.
